### ISSUE TITLE
Most of the time it loads with no content.

### ISSUE THREAD

**Issue by jlybbert** [craigmhughes/TidyTube#6]
The page usually loads with no content and ads at the top. Maybe 10% of the time, I get youtube content.

**Comment by craigmhughes** [comment]
Sorry for not answering this. 

I remember a small issue when this was first released with youtube not feeding enough content for this extension to work properly. This was fixed by adding some manipulation to one of the scroll bars which forces more content to load.

If this is still an issue please let me know.

**_NOTE:_**
**The ads are not from the extension** and if they're an issue, I suggest using an ad blocker.
